const plants = [
  {name:'Serviceberry', latin:'Amelanchier', kind:'Fruit · Native', goal:'fruit', light:'Sun to part shade', water:'Low water', icon:'berry', regions:['Northeast','Midwest','Southeast','Northwest','Mountain'], desc:'Spring blossoms, summer berries, and lovely fall color.'},
  {name:'Wild strawberry', latin:'Fragaria virginiana', kind:'Fruit · Groundcover', goal:'fruit', light:'Sun to part shade', water:'Moderate water', icon:'strawberry', regions:['Northeast','Midwest','Southeast','Northwest','Mountain'], desc:'A sweet, low-growing edible that brings birds and pollinators.'},
  {name:'Blueberry', latin:'Vaccinium', kind:'Fruit · Shrub', goal:'fruit', light:'Full sun', water:'Regular water', icon:'blueberry', regions:['Northeast','Midwest','Southeast','Northwest'], desc:'Spring flowers and summer fruit; likes naturally acidic soil.'},
  {name:'Purple coneflower', latin:'Echinacea purpurea', kind:'Flower · Pollinator favorite', goal:'flowers', light:'Full sun', water:'Low water', icon:'coneflower', regions:['Northeast','Midwest','Southeast','Mountain'], desc:'A long-blooming native that keeps bees and butterflies busy.'},
  {name:'Black-eyed Susan', latin:'Rudbeckia hirta', kind:'Flower · Easygoing', goal:'flowers', light:'Full sun', water:'Low water', icon:'susan', regions:['Northeast','Midwest','Southeast','Mountain'], desc:'Sunny golden blooms that handle heat and poorer soils.'},
  {name:'Wild bergamot', latin:'Monarda fistulosa', kind:'Flower · Pollinator favorite', goal:'flowers', light:'Sun to part shade', water:'Low water', icon:'bergamot', regions:['Northeast','Midwest','Southeast','Northwest','Mountain'], desc:'Lavender blooms with a minty scent, loved by native bees.'},
  {name:'Inkberry holly', latin:'Ilex glabra', kind:'Privacy · Evergreen', goal:'privacy', light:'Sun to part shade', water:'Moderate water', icon:'inkberry', regions:['Northeast','Southeast'], desc:'A tidy native evergreen hedge that stays leafy through winter.'},
  {name:'Eastern red cedar', latin:'Juniperus virginiana', kind:'Privacy · Evergreen', goal:'privacy', light:'Full sun', water:'Low water', icon:'cedar', regions:['Northeast','Midwest','Southeast','Mountain'], desc:'A hardy, wildlife-friendly screen with year-round cover.'},
  {name:'American arborvitae', latin:'Thuja occidentalis', kind:'Privacy · Evergreen', goal:'privacy', light:'Sun to part shade', water:'Moderate water', icon:'arborvitae', regions:['Northeast','Midwest','Northwest'], desc:'A classic dense screen; give it enough room to mature.'}
];
const regionAliases = {Northeast:['new england','maine','vermont','new hampshire','massachusetts','rhode island','connecticut','new york','new jersey','pennsylvania','maryland','delaware'],Midwest:['ohio','michigan','indiana','illinois','wisconsin','minnesota','iowa','missouri','north dakota','south dakota','nebraska','kansas'],Southeast:['virginia','west virginia','kentucky','tennessee','north carolina','south carolina','georgia','florida','alabama','mississippi','arkansas','louisiana','texas'],Northwest:['washington','oregon','idaho'],Mountain:['montana','wyoming','colorado','new mexico','arizona','utah','nevada']};
const state={goal:'all',location:'',region:'',photo:false,photoUrl:'',lightClue:'',stage:0,sceneAnalysis:null,visualRender:0};
const plantTraits={berry:{heightFt:6,establishYears:7},strawberry:{heightFt:.7,establishYears:2},blueberry:{heightFt:5,establishYears:6},coneflower:{heightFt:4,establishYears:2},susan:{heightFt:2.5,establishYears:2},bergamot:{heightFt:4,establishYears:2},inkberry:{heightFt:7,establishYears:8},cedar:{heightFt:14,establishYears:12},arborvitae:{heightFt:12,establishYears:10}};
const sceneAspect=1.6;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const supportedImageTypes=new Set(['image/jpeg','image/png','image/webp']);
const isSupportedImage=file=>Boolean(file&&supportedImageTypes.has(file.type.toLowerCase()));
const toast=$('#toast');let toastTimer;
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3200)}
function detectRegion(value){const v=value.trim().toLowerCase();const zip=v.match(/\b(\d{5})(?:-\d{4})?\b/);if(zip){const prefix=Number(zip[1].slice(0,3));if(prefix>=10&&prefix<=199)return 'Northeast';if(prefix>=200&&prefix<=399)return 'Southeast';if(prefix>=400&&prefix<=699)return 'Midwest';if(prefix>=700&&prefix<=799)return 'Southeast';if(prefix>=800&&prefix<=899)return 'Mountain';if(prefix>=970&&prefix<=999)return 'Northwest'}for(const [region,terms] of Object.entries(regionAliases))if(terms.some(term=>v.includes(term)))return region;const stateCode=(v.match(/(?:^|[,\s])([a-z]{2})(?:$|[,\s])/i)||[])[1]?.toUpperCase();const codes={ME:'Northeast',VT:'Northeast',NH:'Northeast',MA:'Northeast',RI:'Northeast',CT:'Northeast',NY:'Northeast',NJ:'Northeast',PA:'Northeast',MD:'Northeast',DE:'Northeast',OH:'Midwest',MI:'Midwest',IN:'Midwest',IL:'Midwest',WI:'Midwest',MN:'Midwest',IA:'Midwest',MO:'Midwest',ND:'Midwest',SD:'Midwest',NE:'Midwest',KS:'Midwest',VA:'Southeast',WV:'Southeast',KY:'Southeast',TN:'Southeast',NC:'Southeast',SC:'Southeast',GA:'Southeast',FL:'Southeast',AL:'Southeast',MS:'Southeast',AR:'Southeast',LA:'Southeast',TX:'Southeast',WA:'Northwest',OR:'Northwest',ID:'Northwest',MT:'Mountain',WY:'Mountain',CO:'Mountain',NM:'Mountain',AZ:'Mountain',UT:'Mountain',NV:'Mountain'};return codes[stateCode]||''}
function plantArt(type){const flowers={coneflower:['#cf86b5','#814f86'],susan:['#edbb46','#75432a'],bergamot:['#c890b3','#795487']};const berries=['berry','strawberry','blueberry'].includes(type);const flower=flowers[type];let bloom='';if(flower){bloom=`<g transform="translate(160 55)" fill="${flower[0]}"><ellipse cy="-13" rx="4" ry="13"/><ellipse cy="-13" rx="4" ry="13" transform="rotate(45)"/><ellipse cy="-13" rx="4" ry="13" transform="rotate(90)"/><ellipse cy="-13" rx="4" ry="13" transform="rotate(135)"/><ellipse cy="-13" rx="4" ry="13" transform="rotate(180)"/><ellipse cy="-13" rx="4" ry="13" transform="rotate(225)"/><ellipse cy="-13" rx="4" ry="13" transform="rotate(270)"/><ellipse cy="-13" rx="4" ry="13" transform="rotate(315)"/><circle r="6" fill="${flower[1]}"/></g>`}const shrubs=type==='inkberry'||type==='cedar'||type==='arborvitae';const backdrop=berries?'#f0e9d8':flower?'#f3ebdc': '#e8eee2';let growth=shrubs?`<path d="M160 99V40 M160 65L136 78 M160 59L182 74 M160 49L146 60 M160 48L174 59" stroke="#496849" stroke-width="4" stroke-linecap="round"/><path d="M160 34L145 55L160 50L175 57Z" fill="#708f69"/>`: `<path d="M160 108V57 M160 82L137 67 M160 88L183 69 M160 72L145 58 M160 77L175 57" fill="none" stroke="#63825d" stroke-width="3" stroke-linecap="round"/><ellipse cx="142" cy="66" rx="9" ry="4" transform="rotate(25 142 66)" fill="#80986c"/><ellipse cx="179" cy="68" rx="9" ry="4" transform="rotate(-24 179 68)" fill="#82996d"/>`;
  let fruit='';if(berries){const col=type==='blueberry'?'#6876a2':type==='strawberry'?'#d46e58':'#813f59';fruit=`<circle cx="146" cy="82" r="4" fill="${col}"/><circle cx="169" cy="84" r="4" fill="${col}"/><circle cx="157" cy="70" r="4" fill="${col}"/>`}
  return `<svg viewBox="0 0 320 125" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><rect width="320" height="125" fill="${backdrop}"/><circle cx="255" cy="27" r="17" fill="#f3dfa0" opacity=".85"/><path d="M0 105Q80 87 162 103T320 96V125H0Z" fill="#cfdbc2"/>${growth}${fruit}${bloom}<path d="M0 115Q80 108 145 117T320 111" fill="none" stroke="#abc09b" stroke-width="1"/></svg>`;
}
function plantPortrait(type){
  const palettes={berry:['#58764d','#718f59','#9f505b'],strawberry:['#61864e','#83a15c','#ca5c4b'],blueberry:['#54754c','#829764','#67759a'],coneflower:['#53754b','#86a266','#d393bb'],susan:['#55764d','#88a05c','#f0bd49'],bergamot:['#4d714a','#789360','#b58bc7'],inkberry:['#355a40','#527b4c','#283a30'],cedar:['#3e6548','#55794c','#678259'],arborvitae:['#436a4c','#658458','#7c9968']};
  const [stem,leaf,accent]=palettes[type]||palettes.berry;
  const shrub=['berry','blueberry','inkberry','cedar','arborvitae'].includes(type);
  const ground=type==='strawberry';
  let body='';
  if(shrub&&['cedar','arborvitae'].includes(type)){
    body=`<path d="M80 235L80 70Q80 44 93 30Q105 45 106 65L111 96L132 59Q142 46 153 50L136 99L164 83Q177 76 183 85L157 112L176 114Q188 119 184 130L151 128L168 148Q175 162 166 169L139 143L147 179Q149 193 138 197L116 161L118 207Q114 220 104 212L99 170L89 221Z" fill="${leaf}"/><path d="M101 224L103 86" stroke="${stem}" stroke-width="7"/>`;
  }else if(shrub){
    body=`<path d="M104 226V112" stroke="${stem}" stroke-width="7"/><g fill="${leaf}"><circle cx="85" cy="107" r="35"/><circle cx="126" cy="98" r="38"/><circle cx="72" cy="145" r="34"/><circle cx="129" cy="145" r="42"/><circle cx="101" cy="73" r="33"/></g><g fill="${accent}"><circle cx="75" cy="103" r="3"/><circle cx="126" cy="115" r="3"/><circle cx="91" cy="143" r="3"/><circle cx="139" cy="148" r="3"/><circle cx="102" cy="78" r="3"/></g>`;
  }else if(ground){
    body=`<path d="M87 220Q91 129 73 80M94 200Q126 129 149 74M92 176Q68 129 46 121M96 156Q123 134 154 132" fill="none" stroke="${stem}" stroke-width="6" stroke-linecap="round"/><g fill="${leaf}"><path d="M69 104Q35 63 55 52Q82 57 84 89Q94 60 114 64Q122 91 91 111Q125 106 131 128Q108 151 86 124Q92 159 68 165Q45 146 69 119Q36 133 28 114Q40 91 69 104Z"/><path d="M141 102Q108 62 127 51Q151 58 153 87Q162 59 183 64Q190 90 160 108Q194 104 200 125Q178 148 155 122Q162 157 138 162Q115 144 140 117Q106 131 99 112Q112 90 141 102Z"/></g><path d="M68 129L57 155 M151 123L165 149" stroke="${accent}" stroke-width="9" stroke-linecap="round"/>`;
  }else{
    const color=type==='coneflower'?'#794f80':type==='susan'?'#805835':'#695282';
    const petals=type==='susan'?'#edbd4e':type==='coneflower'?'#cc8bb3':'#b18ac4';
    let blooms='';
    const centers=type==='coneflower'?[[78,77],[130,54],[106,110]]:[[77,62],[130,82],[104,45]];
    centers.forEach(([x,y])=>{blooms+=`<g transform="translate(${x} ${y})" fill="${petals}"><ellipse cy="-19" rx="6" ry="17"/><ellipse cy="-19" rx="6" ry="17" transform="rotate(45)"/><ellipse cy="-19" rx="6" ry="17" transform="rotate(90)"/><ellipse cy="-19" rx="6" ry="17" transform="rotate(135)"/><circle r="8" fill="${color}"/></g>`});
    body=`<path d="M100 236Q101 180 77 97M101 230Q119 153 131 83M102 205Q73 161 55 149M105 188Q140 157 162 151" fill="none" stroke="${stem}" stroke-width="5" stroke-linecap="round"/><g fill="${leaf}"><ellipse cx="66" cy="160" rx="20" ry="8" transform="rotate(32 66 160)"/><ellipse cx="140" cy="171" rx="21" ry="8" transform="rotate(-26 140 171)"/><ellipse cx="89" cy="197" rx="19" ry="7" transform="rotate(28 89 197)"/></g>${blooms}`;
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 210 250"><ellipse cx="105" cy="238" rx="58" ry="7" fill="#304b3824"/>${body}<path d="M36 238H174" stroke="#718a55" stroke-width="3" stroke-linecap="round"/></svg>`;
}
function getPlants(){let list=plants.filter(p=>state.goal==='all'||p.goal===state.goal);if(state.region){const local=list.filter(p=>p.regions.includes(state.region));if(local.length)list=local;else list=list.slice(0,6)}if(state.lightClue==='shadier')list.sort((a,b)=>Number(b.light==='Sun to part shade')-Number(a.light==='Sun to part shade'));return list.slice(0,6)}
function render(){const list=getPlants();$('#plantGrid').innerHTML=list.map(p=>`<article class="plant-card"><div class="plant-art">${plantArt(p.icon)}<span class="sun-pill">☼ ${p.light}</span></div><div class="plant-info"><div class="plant-kind">${p.kind}</div><div class="plant-name">${p.name}</div><div class="plant-desc">${p.desc}</div><div class="plant-meta"><span>♧ ${p.water}</span><span>${p.latin}</span></div></div></article>`).join('');const labels={all:'All goals',fruit:'Fruits & food',flowers:'Flowers & pollinators',privacy:'Privacy & screening'};$('#filterLabel span').textContent=labels[state.goal];$('#resultsSubtitle').textContent=state.region?`A first look at plants suited to the ${state.region}${state.photo?` and your ${state.lightClue==='shadier'?'darker':'brighter'} photo` :''}. Check sun, soil, and local planting guidance before you choose.`:'A thoughtfully chosen mix for your garden. Add a location to make these recommendations local.';if(!list.length)$('#plantGrid').innerHTML='<p>No suggestions for that goal yet. Try another goal.</p>';if(!$('#visualizer').classList.contains('hidden'))renderVisualizer()}
const growthStages=[{name:'Today',badge:'TODAY',years:0,description:'New planting day. Small starts settle into the spots estimated from your photo.'},{name:'1 year',badge:'AFTER 1 YEAR',years:1,description:'Fast-growing perennials fill in first; slower shrubs establish at their own pace.'},{name:'3 years',badge:'AFTER 3 YEARS',years:3,description:'Perennials approach mature size while fruiting and screening shrubs continue to fill out.'},{name:'5 years',badge:'AFTER 5 YEARS',years:5,description:'A more established layout, with each plant scaled by its typical mature height.'}];
const portraitCache=new Map();
function imageForPlant(type){if(!portraitCache.has(type)){portraitCache.set(type,loadImage(`data:image/svg+xml;charset=utf-8,${encodeURIComponent(plantPortrait(type))}`))}return portraitCache.get(type)}
function drawPhotoCover(ctx,image,width,height){const target=width/height,imageAspect=image.naturalWidth/image.naturalHeight;let sx=0,sy=0,sw=image.naturalWidth,sh=image.naturalHeight;if(imageAspect>target){sw=image.naturalHeight*target;sx=(image.naturalWidth-sw)/2}else{sh=image.naturalWidth/target;sy=(image.naturalHeight-sh)/2}ctx.drawImage(image,sx,sy,sw,sh,0,0,width,height)}
function groundPixelScore(r,g,b){if(g>55&&g>r*1.08&&g>b*1.04)return 1;if(r>72&&r>g*1.08&&g>b*1.04&&b<175)return .55;return 0}
function analyzeGardenPhoto(image){const width=160,height=100,sample=document.createElement('canvas');sample.width=width;sample.height=height;const ctx=sample.getContext('2d',{willReadFrequently:true});if(!ctx)return{groundTop:.62,confidence:0,columns:[]};drawPhotoCover(ctx,image,width,height);const pixels=ctx.getImageData(0,0,width,height).data,rowScore=new Array(height).fill(0);let greens=0,total=width*height,brightness=0;for(let y=0;y<height;y++){let score=0;for(let x=0;x<width;x++){const i=(y*width+x)*4,r=pixels[i],g=pixels[i+1],b=pixels[i+2];score+=groundPixelScore(r,g,b);if(g>r*1.08&&g>b*1.04&&g>55)greens++;brightness+=(.2126*r+.7152*g+.0722*b)/255}rowScore[y]=score/width}let groundTop=.62,confidence=0;for(let y=30;y<83;y++){const band=(rowScore[y]+rowScore[y+1]+rowScore[y+2]+rowScore[y+3]+rowScore[y+4])/5;if(band>.19){groundTop=y/height;confidence=band;break}}const columns=[];for(let x=8;x<width-8;x+=3){let score=0,count=0;const from=Math.max(38,Math.floor(groundTop*height)-3);for(let y=from;y<97;y++){for(let dx=-4;dx<=4;dx++){const i=(y*width+x+dx)*4;score+=groundPixelScore(pixels[i],pixels[i+1],pixels[i+2]);count++}}let localTop=groundTop;for(let y=Math.max(30,Math.floor(groundTop*height)-5);y<83;y++){let band=0,bandCount=0;for(let dy=0;dy<4;dy++)for(let dx=-4;dx<=4;dx++){const i=((y+dy)*width+x+dx)*4;band+=groundPixelScore(pixels[i],pixels[i+1],pixels[i+2]);bandCount++}if(band/bandCount>.28){localTop=y/height;break}}columns.push({x:x/width,score:count?score/count:0,groundY:localTop})}return{groundTop,confidence,columns,brightness:brightness/total,greenRatio:greens/total}}
function clamp(value,min,max){return Math.max(min,Math.min(max,value))}
function photoAwareLayout(list,analysis){const count=list.length;if(!count)return[];const columns=analysis?.columns||[],groundTop=analysis?.groundTop??.62,chosen=[];for(let index=0;index<count;index++){const target=(index+1)/(count+1);let best={x:target,score:-Infinity,groundY:groundTop};for(const candidate of columns){if(candidate.x<target-.15||candidate.x>target+.15)continue;if(chosen.some(item=>Math.abs(item.x-candidate.x)<.145))continue;const score=candidate.score*.8-Math.abs(candidate.x-target)*.7;if(score>best.score)best={x:candidate.x,score,groundY:candidate.groundY}}const x=clamp(best.x,.1,.9),nearby=columns.filter(c=>Math.abs(c.x-x)<.07),localQuality=nearby.length?nearby.reduce((sum,c)=>sum+c.score,0)/nearby.length:0,baseY=clamp(best.groundY+.27+(localQuality<.06?.02:0),.73,.96);chosen.push({x,y:baseY,quality:localQuality,index})}return chosen}
function growthFactor(plant,stage){const trait=plantTraits[plant.icon]||{establishYears:5};const rate=2.3/trait.establishYears,years=growthStages[stage].years;return .08+.92*(1-Math.exp(-rate*years))}
function drawPlanBadges(ctx,width,height,stage){const scale=width/1200;ctx.save();ctx.font=`600 ${12*scale}px Arial, sans-serif`;const top=18*scale,left=18*scale;ctx.fillStyle='#ffffffdf';ctx.beginPath();if(ctx.roundRect)ctx.roundRect(left,top,178*scale,26*scale,13*scale);else ctx.rect(left,top,178*scale,26*scale);ctx.fill();ctx.fillStyle='#4e634a';ctx.fillText('FIELDNOTE  ·  GARDEN PLAN',left+12*scale,top+17*scale);const label=growthStages[stage].badge;const labelWidth=ctx.measureText(label).width+22*scale;ctx.fillStyle='#ffffffdf';ctx.beginPath();if(ctx.roundRect)ctx.roundRect(width-left-labelWidth,top,labelWidth,26*scale,13*scale);else ctx.rect(width-left-labelWidth,top,labelWidth,26*scale);ctx.fill();ctx.fillStyle='#627557';ctx.fillText(label,width-left-labelWidth+11*scale,top+17*scale);ctx.restore()}
function paintGardenPlan(ctx,width,height,photo,list,stage,analysis,portraits){drawPhotoCover(ctx,photo,width,height);const shade=ctx.createLinearGradient(0,0,0,height);shade.addColorStop(0,'rgba(26,51,33,.10)');shade.addColorStop(.4,'rgba(26,51,33,0)');shade.addColorStop(1,'rgba(20,43,40,.12)');ctx.fillStyle=shade;ctx.fillRect(0,0,width,height);const placements=photoAwareLayout(list,analysis).map(point=>({plant:list[point.index],...point})).sort((a,b)=>a.y-b.y);for(const item of placements){const trait=plantTraits[item.plant.icon]||{heightFt:4};const perspective=.76+clamp((item.y-.62)/.32,0,1)*.26,plantHeight=height*Math.min(.58,.04+trait.heightFt*.035)*growthFactor(item.plant,stage)*perspective,plantWidth=plantHeight*210/250;ctx.drawImage(portraits[item.plant.icon],item.x*width-plantWidth/2,item.y*height-plantHeight,plantWidth,plantHeight)}drawPlanBadges(ctx,width,height,stage)}
function renderGardenCanvas(){const canvas=$('#gardenCanvas'),ctx=canvas.getContext('2d');if(!ctx)return;const token=++state.visualRender,width=1200,height=Math.round(width/sceneAspect);canvas.width=width;canvas.height=height;const list=getPlants().slice(0,4);Promise.all([loadImage(state.photoUrl),...list.map(p=>imageForPlant(p.icon))]).then(([photo,...portraits])=>{if(token!==state.visualRender||state.photoUrl==='')return;paintGardenPlan(ctx,width,height,photo,list,state.stage,state.sceneAnalysis,Object.fromEntries(list.map((p,i)=>[p.icon,portraits[i]])));canvas.setAttribute('aria-label',`Illustrated garden plan, ${growthStages[state.stage].name}, including ${list.map(p=>p.name).join(', ')}`)}).catch(()=>{if(token===state.visualRender)showToast('Could not render the garden preview from this image.')})}
function renderVisualizer(){const list=getPlants().slice(0,4),stage=growthStages[state.stage];$('#growthYear').textContent=stage.name;$('#growthDescription').textContent=stage.description;$('#growthSlider').value=state.stage;$$('.growth-tick').forEach(t=>t.classList.toggle('active',Number(t.dataset.stage)===state.stage));$('#includedPlants').innerHTML=list.map(p=>`<span class="included-plant"><span>✳</span>${p.name}</span>`).join('');renderGardenCanvas()}
function inspectPhoto(img){try{const analysis=analyzeGardenPhoto(img);state.sceneAnalysis=analysis;state.lightClue=analysis.brightness<.37?'shadier':'brighter';$('#photoClue').textContent=`${state.lightClue==='shadier'?'Darker':'Brighter'} photo${analysis.greenRatio>.22?' · leafy color':''}`;render()}catch{state.sceneAnalysis={groundTop:.62,confidence:0,columns:[]};$('#photoClue').textContent='Photo added';state.lightClue='';render()}}
function setLocation(value,region=''){state.location=value;state.region=region||detectRegion(value);$('#locationInput').value=value;$('#sidebarPlace').textContent=value||'Your garden';$('#sidebarClimate').textContent=state.region?`${state.region} · regional plants`:value?'Location added':'Set your location';$('#locationHint').textContent=state.region?`Showing plants suited to the ${state.region}, matched on this device.`:value?'No regional match yet. Add a state or U.S. ZIP for broad matching.':'Optional. We match broad regions on this device.';render()}
function handlePhoto(file){if(!isSupportedImage(file)){showToast('Choose a JPEG, PNG, or WebP photo.');return}if(file.size>25*1024*1024){showToast('That image is over 25 MB. Choose a smaller photo to keep processing smooth.');return}const url=URL.createObjectURL(file),img=$('#previewImg'),previousUrl=state.photoUrl,previousName=$('#photoName').textContent,previousClue=$('#photoClue').textContent;$('#photoClue').textContent='Reading photo clues…';img.onload=()=>{if(previousUrl&&previousUrl!==url)URL.revokeObjectURL(previousUrl);state.photoUrl=url;state.photo=true;state.sceneAnalysis=null;$('#photoName').textContent=file.name||'Pasted garden photo';$('#uploadEmpty').classList.add('hidden');$('#photoPreview').classList.remove('hidden');inspectPhoto(img);showToast('Photo added. Your garden preview is ready.')};img.onerror=()=>{URL.revokeObjectURL(url);img.onload=null;img.onerror=null;if(previousUrl){img.src=previousUrl;$('#photoName').textContent=previousName;$('#photoClue').textContent=previousClue;state.photo=true;showToast('That image could not be opened. Your previous photo is still in place.')}else{state.photo=false;state.photoUrl='';$('#photoPreview').classList.add('hidden');$('#uploadEmpty').classList.remove('hidden');$('#photoClue').textContent='';showToast('This image could not be opened. Try a JPEG, PNG, or WebP photo.')}};img.src=url}
$('#choosePhoto').addEventListener('click',()=>$('#photoInput').click());$('#changePhoto').addEventListener('click',()=>$('#photoInput').click());$('#photoInput').addEventListener('change',e=>{handlePhoto(e.target.files[0]);e.target.value='' });
let dragDepth=0;const dropOverlay=$('#dropOverlay');function hasDraggedFile(event){return Array.from(event.dataTransfer?.types||[]).some(type=>type.toLowerCase()==='files')}document.addEventListener('dragenter',event=>{if(!hasDraggedFile(event))return;event.preventDefault();dragDepth++;dropOverlay.classList.add('active')});document.addEventListener('dragover',event=>{if(!hasDraggedFile(event))return;event.preventDefault();if(event.dataTransfer)event.dataTransfer.dropEffect='copy'});document.addEventListener('dragleave',event=>{if(!hasDraggedFile(event))return;dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)dropOverlay.classList.remove('active')});document.addEventListener('drop',event=>{if(!hasDraggedFile(event))return;event.preventDefault();dragDepth=0;dropOverlay.classList.remove('active');const file=Array.from(event.dataTransfer.files||[]).find(isSupportedImage);if(file)handlePhoto(file);else showToast('Drop a JPEG, PNG, or WebP photo.')});document.addEventListener('paste',event=>{const item=Array.from(event.clipboardData?.items||[]).find(entry=>supportedImageTypes.has(entry.type.toLowerCase()));if(!item)return;const file=item.getAsFile();if(file){event.preventDefault();handlePhoto(file)}});
$$('.goal-chip').forEach(btn=>btn.addEventListener('click',()=>{$$('.goal-chip').forEach(c=>c.classList.remove('selected'));btn.classList.add('selected');state.goal=btn.dataset.goal;render()}));
$('#locationInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const value=e.currentTarget.value.trim();if(value)setLocation(value);e.currentTarget.blur()}});$('#locationInput').addEventListener('change',e=>{const value=e.target.value.trim();if(value)setLocation(value)});
$('#findPlants').addEventListener('click',()=>{render();document.querySelector('.results').scrollIntoView({behavior:'smooth',block:'start'});if(!state.photo&&!state.location)showToast('Add a photo and location for ideas tailored to your space.');else if(!state.location)showToast('Add your location to see regionally suited plants.');else if(!state.photo)showToast('Add a photo to help you think through your space.');else showToast('Your garden ideas are ready below.')});
$('#visualizeButton').addEventListener('click',()=>{if(!state.photo){showToast('Add a garden photo first to preview your planting plan.');$('#photoInput').click();return}$('#visualizer').classList.remove('hidden');renderVisualizer();$('#visualizer').scrollIntoView({behavior:'smooth',block:'start'})});$('#closeVisualizer').addEventListener('click',()=>$('#visualizer').classList.add('hidden'));$('#growthSlider').addEventListener('input',e=>{state.stage=Number(e.target.value);renderVisualizer()});$$('.growth-tick').forEach(t=>t.addEventListener('click',()=>{state.stage=Number(t.dataset.stage);renderVisualizer()}));
function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src})}
$('#downloadVisual').addEventListener('click',async()=>{if(!state.photoUrl){showToast('Add a garden photo before saving a concept.');return}try{const photo=await loadImage(state.photoUrl),canvas=document.createElement('canvas');canvas.width=2400;canvas.height=Math.round(canvas.width/sceneAspect);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas is unavailable');const list=getPlants().slice(0,4),portraits=await Promise.all(list.map(p=>imageForPlant(p.icon)));paintGardenPlan(ctx,canvas.width,canvas.height,photo,list,state.stage,state.sceneAnalysis,Object.fromEntries(list.map((p,i)=>[p.icon,portraits[i]])));canvas.toBlob(blob=>{if(!blob){showToast('Could not save this preview.');return}const imageUrl=URL.createObjectURL(blob),link=document.createElement('a');link.href=imageUrl;link.download=`fieldnote-garden-${state.stage===0?'today':state.stage===1?'year-1':state.stage===2?'year-3':'year-5'}.png`;link.click();setTimeout(()=>URL.revokeObjectURL(imageUrl),1000);showToast('Garden concept saved as an image.')},'image/png')}catch{showToast('Could not create the image. Try another garden photo.')}});
window.addEventListener('pagehide',()=>{if(state.photoUrl)URL.revokeObjectURL(state.photoUrl)});
$('#howItWorks').addEventListener('click',()=>$('#infoDialog').showModal());$('#closeDialog').addEventListener('click',()=>$('#infoDialog').close());$('#gotIt').addEventListener('click',()=>$('#infoDialog').close());$('#infoDialog').addEventListener('click',e=>{if(e.target===$('#infoDialog'))$('#infoDialog').close()});$('#sidebarLocation').addEventListener('click',()=>{$('#locationInput').focus();document.querySelector('.workspace').scrollIntoView({behavior:'smooth',block:'center'})});$('#viewAll').addEventListener('click',()=>showToast('More plant ideas are on their way. Start with these locally suited picks.'));
render();
